"""Workpaper verification ID generation and verification.

Every generated workpaper receives a tamper-evident ID in the format:
    PF-{engine_version}-{YYYYMMDD}-{uid8}-{hmac8}

Example: PF-1.0.0-20260318-A3F9C2B1-D84E7A19

The HMAC-SHA256 signature is computed over the payload:
    "PF|{engine_version}|{YYYYMMDD}|{uid8}"

using the VERIFICATION_SECRET environment variable.  The signature makes the
ID unforgeable without the secret key -- a property no internal spreadsheet
tool can replicate.

The default secret "portfolioforge-dev" is for local/test use only.  Production
deployments must set VERIFICATION_SECRET to a strong random value via environment
variable or Streamlit secrets.
"""

from __future__ import annotations

import hashlib
import hmac as hmac_module
import os
import uuid
from dataclasses import dataclass, field
from datetime import date

from market_data.backtest.tax.engine import TAX_ENGINE_VERSION

_DEFAULT_SECRET = "portfolioforge-dev"
_PREFIX = "PF"
_UID_LEN = 8
_SIG_LEN = 8


def _secret() -> str:
    return os.getenv("VERIFICATION_SECRET", _DEFAULT_SECRET)


def _compute_sig(engine_version: str, gen_date: str, uid: str) -> str:
    """Return first _SIG_LEN hex chars of HMAC-SHA256(secret, payload), uppercase."""
    payload = f"{_PREFIX}|{engine_version}|{gen_date}|{uid}"
    raw = hmac_module.new(
        _secret().encode(),
        payload.encode(),
        hashlib.sha256,
    ).hexdigest()
    return raw[:_SIG_LEN].upper()


def generate_workpaper_id(generation_date: date | None = None) -> str:
    """Generate a tamper-evident workpaper verification ID.

    Args:
        generation_date: Override the generation date (defaults to today).

    Returns:
        Verification ID string, e.g. "PF-1.0.0-20260318-A3F9C2B1-D84E7A19".
    """
    engine_version = TAX_ENGINE_VERSION
    gen_date = (generation_date or date.today()).strftime("%Y%m%d")
    uid = uuid.uuid4().hex[:_UID_LEN].upper()
    sig = _compute_sig(engine_version, gen_date, uid)
    return f"{_PREFIX}-{engine_version}-{gen_date}-{uid}-{sig}"


@dataclass
class VerificationResult:
    """Result of a workpaper ID verification check."""

    valid: bool
    engine_version: str = field(default="")
    generation_date: str = field(default="")  # YYYYMMDD
    reason: str = field(default="")

    def display_date(self) -> str:
        """Return generation_date as DD Mon YYYY, or empty string if invalid."""
        if len(self.generation_date) != 8 or not self.generation_date.isdigit():
            return ""
        from datetime import datetime

        try:
            return datetime.strptime(self.generation_date, "%Y%m%d").strftime("%d %b %Y")
        except ValueError:
            return self.generation_date


def verify_workpaper_id(id_str: str) -> VerificationResult:
    """Verify a workpaper ID and return the embedded metadata.

    Args:
        id_str: Workpaper ID string (case-insensitive).

    Returns:
        VerificationResult with valid=True and metadata on success,
        or valid=False with a reason string on failure.
    """
    if not id_str or not id_str.strip():
        return VerificationResult(valid=False, reason="Empty ID")

    normalised = id_str.strip().upper()
    parts = normalised.split("-")

    # Expected: ["PF", "1.0.0", "YYYYMMDD", "UID8", "SIG8"]
    if len(parts) != 5:
        return VerificationResult(
            valid=False,
            reason=f"Invalid format -- expected 5 dash-separated parts, got {len(parts)}",
        )

    prefix, engine_version, gen_date, uid, sig = parts

    if prefix != _PREFIX:
        return VerificationResult(valid=False, reason="Invalid prefix -- not a PortfolioForge ID")

    if not (gen_date.isdigit() and len(gen_date) == 8):
        return VerificationResult(valid=False, reason="Invalid date component in ID")

    expected_sig = _compute_sig(engine_version, gen_date, uid)

    if sig != expected_sig:
        return VerificationResult(
            valid=False,
            reason="Signature mismatch -- ID may be tampered or not generated by this engine",
        )

    return VerificationResult(
        valid=True,
        engine_version=engine_version,
        generation_date=gen_date,
    )
